### PR TITLE
Remove code that requires C++11 features

### PR DESCRIPTION
**Pull request by federicofernandez**
To allow compilation in Windows + Python 2.7 we need to remove the use of lambdas and std::function since is not supported in the msvc compiler version for 2.7.

Fixes: https://ci.appveyor.com/project/conda-forge/pandana-feedstock/builds/27034085/job/nwh0feurg1ijv0eu

### CODE REVIEW

**Comment by smmaurer** [comment]
Thanks @federicofernandez! 

One of the compilation flags in `setup.py` specifies `std=c++11`. Do you think we should change that? It might not matter; i think that's been there since before the changes that broke win-py27 compilation.

https://github.com/UDST/pandana/blob/enhancement/remove-c%2B%2B11/setup.py#L54

**Comment by federicofernandez** [comment]
> One of the compilation flags in setup.py specifies std=c++11. Do you think we should change that? It might not matter; i think that's been there since before the changes that broke win-py27 compilation.

I don't think is needed since those flags are used only for Linux / OSX. Anyway, the final test will be the compilation on Windows + 2.7, but I think it should work as is.

**Comment by Eh2406** [comment]
Can we make sure the performance does not regress, that we still have the gains from #111?

**Comment by federicofernandez** [comment]
Yes, no regressions, it's the same performance as #111, just with less elegant code, but more compatible.

**Comment by Eh2406** [comment]
Thanks for double checking!

**Pull request merged**
